<!-- Start Server information Module -->
<div class='block'>
	<h3>Server Information</h3>
	<?php

	$safe_mode = ini_get('safe_mode') ? ini_get('safe_mode') : 'Off';
	$upload_max = ini_get('upload_max_filesize') ? ini_get('upload_max_filesize') : 'N/A';
	$post_max = ini_get('post_max_size') ? ini_get('post_max_size') : 'N/A';
	$memory_limit = ini_get('memory_limit') ? ini_get('memory_limit') : 'N/A';
	$allow_url_fopen = ini_get('allow_url_fopen') ? 'On' : 'Off';
	$cURL = function_exists('curl_version') ? 'On' : 'Off';
	$permalinks = get_option('permalink_structure') ? 'On' : 'Off';

	$php_info = cminds_parse_php_info();

	?>
	<span class="description">This information is useful to check if plugin might have some incompabilities with you server.</span>
	<table class="form-table server-info-table">
	    <tr>
	        <th>PHP Version:</th>
	        <td><?php echo phpversion(); ?></td>
	        <td><?php if (version_compare(phpversion(), '5.3.0', '<')): ?><strong>Recommended 5.3 or higher</strong><?php else: ?><span>OK</span><?php endif; ?></td>
	    </tr>
	    <tr>
			<th>PHP Safe Mode:</th>
			<td><?php echo $safe_mode; ?></td>
			<td><?php if (version_compare(phpversion(), '5.3.0', '<')): ?><strong>Safe mode is deprecated</strong><?php else: ?><span>OK</span><?php endif; ?></td>
		</tr>
	    <tr>
	        <th>PHP Max Upload Size:</th>
	        <td><?php echo $upload_max; ?></td>
	        <td><?php if (cminds_units2bytes($upload_max) < 1024*1024*5): ?>
	        	<strong>This value can be too lower to upload large files.</strong>
	        <?php else: ?><span>OK</span><?php endif; ?></td>
	    </tr>
	    <tr>
	        <th>PHP Max Post Size:</th>
	        <td><?php echo $post_max; ?></td>
	        <td><?php if (cminds_units2bytes($post_max) < 1024*1024*2): ?>
	        	<strong>This value can be too lower to upload large files.</strong>
	        <?php else: ?><span>OK</span><?php endif; ?></td>
	    </tr>
	    <tr>
	        <th>PHP Memory Limit:</th>
	        <td><?php echo $memory_limit; ?></td>
	        <td><?php if (cminds_units2bytes($memory_limit) < 1024*1024*128): ?>
	        	<strong>This value can be too lower to Wordpress with plugins work properly.</strong>
	        <?php else: ?><span>OK</span><?php endif; ?></td>
	    </tr>
	    <tr>
	        <th>PHP cURL:</th>
	        <td><?php echo $cURL; ?></td>
	        <td><?php if ($cURL == 'Off'): ?>
	        	<strong>cURL library is required to use the Social Login.</strong>
	        <?php else: ?><span>OK</span><?php endif; ?></td>
	    </tr>
	    <tr>
	        <th>WP permalinks:</th>
	        <td><?php echo $permalinks; ?></td>
	        <td><?php if ($permalinks == 'Off'): ?>
	        	<strong>Permalinks in Wordpress are required.</strong>
	        <?php else: ?><span>OK</span><?php endif; ?></td>
	    </tr>
	    <tr>
	    	<th>PHP allow URL fopen:</th>
	        <td><?php echo $allow_url_fopen; ?></td>
	        <td><?php if ($allow_url_fopen == 'Off'): ?>
	        	<strong>cURL library is required to use the Social Login.</strong>
	        <?php else: ?><span>OK</span><?php endif; ?></td>
	    </tr>

	    <?php
	    if( isset($php_info['gd']) && is_array($php_info['gd']) )
	    {
	        foreach($php_info['gd'] as $key => $val)
	        {
	            if( !preg_match('/(WBMP|XBM|Freetype|T1Lib)/i', $key) && $key != 'Directive' && $key != 'gd.jpeg_ignore_warning' )
	            {
		echo '<tr>';
		echo '<th>' . $key . ':</th>';
		if( stripos($key, 'support') === false )
		{
		    echo '<td>' . $val . '</td>';
		}
		else
		{
			$val = true;
		    echo '<td>enabled</td>';
		}

		echo '<td>';
		switch ($key) {
									case 'GD Support':
										if ($val === true) echo '<span>OK</span>';
										else echo '<strong>Required to display screenshots.</strong>';
										break;

								}
								echo '</td>';
		echo '</tr>';
	            }
	        }
	    }
	    ?>
	</table>
</div>