<style>
    div.cmob-upgrade {
        display: inline-block;
        padding: 1em;
        background: #FFF;
        border: solid 1px #E0E0E0;
        max-width: 650px;
        margin: 1em 0;
    }
</style>

<div class="cmob-upgrade">
    <h3>Want more? Get the PRO</h3>
    <p>Professional version of <?php echo CMOB_NAME; ?> which gives the admin better tools to customize the On Boarding system behavior:
        adding customization options (icons, position, widget types), themes, headers/footers and a lot more. </p>
    <a href="<?php echo esc_attr(admin_url('admin.php?page=' . CMOB_PRO_OPTION)); ?>" class="button button-primary">Upgrade to PRO</a>
</div>