<?php
get_header();
the_post();
$thread = CMA_AnswerThread::getInstance($post->ID);
?>
<div id="primary" class="site-content">
    <div id="content" role="main">
        <header class="entry-header">
        <h1 class="entry-title"><?php echo $thread->getTitle(); ?><a class="cma-backlink" href="<?php echo get_post_type_archive_link(CMA_AnswerThread::POST_TYPE); ?>">&laquo; Back to Questions List</a></h1>
        
        </header>
        <?php
        do_action('CMA_show_messages');
        ?>
        <?php if (CMA_AnswerThread::isRatingAllowed()): ?>
        <script type="text/javascript">
            function thumbsUp(comment_id) {
                thumbs(comment_id, 'up');
            }
        <?php if (CMA_AnswerThread::isNegativeRatingAllowed()): ?>function thumbsDown(comment_id) {
                thumbs(comment_id, 'down');
            }<?php endif; ?>
    function thumbs(comment_id, upDown) {
        jQuery('#comment-'+comment_id+' .cma-answer-rating-loading').show();
        jQuery.post(self.location, {'cma-action': 'vote', 'cma-comment': comment_id, 'cma-value': upDown}, function(data) {
            if (data.success==1) {
                jQuery('#comment-'+comment_id+' .cma-answer-rating-count').text(data.message);
                jQuery().toastmessage('showSuccessToast', "Thank you for voting!");
            } else {
                jQuery().toastmessage('showErrorToast', data.message);
            }
            jQuery('#comment-'+comment_id+' .cma-answer-rating-loading').hide();
        });
    }    
    </script>
    <?php endif; ?>
        <table class="cma-answers-list">
            <tr>
                <td class="cma-answer-content">
                    <div class="cma-answer-body"><?php echo $thread->getContent(); ?></div>
                    <div class="cma-answer-meta">
                        <div class="cma-answer-author">Posted by <?php echo $thread->getAuthor()->display_name; ?></div>
                        <div class="cma-answer-date">Asked on <?php echo $thread->getCreationDate(); ?></div>
                    </div>
                </td>
            </tr>
			</table>
 
            <?php
            
            $currentSort = !empty($_GET['sort'])?$_GET['sort']:'newest';
            $answers = $thread->getAnswers($currentSort);
            if (!empty($answers)): ?>
    <?php if (CMA_AnswerThread::isRatingAllowed()): ?><ul class="cma-thread-orderby cma-answers-orderby">
                <li<?php if ($currentSort=='newest'):?> class="cma-current-sort"<?php endif; ?>><a href="?sort=newest">Newest</a></li>
                <li<?php if ($currentSort=='votes'):?> class="cma-current-sort"<?php endif; ?>><a href="?sort=votes">Highest Rating</a></li>
            </ul><?php endif; ?>
    <?php
            foreach ($answers as $answer):
                ?>
			<table class="cma-answers-list">
                <tr id="comment-<?php echo $answer['id']; ?>">
                    <?php if (CMA_AnswerThread::isRatingAllowed()): ?><td class="cma-answer-rating" >
                        <div class="cma-answer-rating-loading"></div>
                        <a href="javascript:void(0)" onclick="thumbsUp(<?php echo $answer['id']; ?>)" class="cma-thumbs-up" title="Thumbs Up!">▲</a>
                        <div class="cma-answer-rating-count"><?php echo $answer['rating']; ?></div>
                        <?php if (CMA_AnswerThread::isNegativeRatingAllowed()): ?><a href="javascript:void(0)" onclick="thumbsDown(<?php echo $answer['id']; ?>)" class="cma-thumbs-down" title="Thumbs Down!">▼</a><?php endif; ?>
                        
                    </td>
                        <?php else: ?>
                    <td class="cma-answer-norating"></td>
                        <?php endif; ?>

                    <td class="cma-answer-content<?php if (CMA_AnswerThread::isRatingAllowed()): ?> cma-answer-norating-content<?php endif; ?>">
                        <div class="cma-answer-body"><?php echo $answer['content']; ?></div>
                        <div class="cma-answer-meta">
                            <div class="cma-answer-author">Posted by <?php echo $answer['author']; ?></div>
                            <div class="cma-answer-date">Answered On <?php echo $answer['date']; ?> <a href="#comment-<?php echo $comment->comment_ID; ?>">#</a></div>
                        </div>
                    </td>
                </tr>
                <?php
            endforeach;
            endif;
            ?>
        </table>
        <div class="cma-form-container">
             <?php if (is_user_logged_in() && !$thread->isResolved()): ?>
     		<div style="clear:both;height:25px;"></div>		
    <form method="post">
            <input type="hidden" name="cma-action" value="add" />
            <h3>Post your Answer</h3>
			<div style="clear:both;height:10px;"></div>	
             <ul class="cma-form-notes">
            <li>Allow markup: &lt;strong&gt;, &lt;em&gt;, &lt;a&gt;</li>
            <li>Wrap your code using &lt;pre&gt;&lt;/pre&gt;</li>
        </ul>
            <input type="hidden" name="cma-thread" value="<?php echo $post->ID; ?>"/>
            <textarea name="content" placeholder="Write your Answer here"></textarea><br />
            <label>
     		<div style="clear:both;height:5px;"></div>	
           <input name="thread_notify" type="checkbox" value="1"/>
            Notify me of follow</label><br />
            <?php if (get_current_user_id()==$thread->getAuthorId()): ?><label>
     		<div style="clear:both;height:5px;"></div>	
           <input name="thread_resolved" type="checkbox" value="1"/>
            Mark as resolved</label><br /><?php endif; ?>
 			<div style="clear:both;height:10px;"></div>	
            <input type="submit" value="Post your Answer" />
        </form>
            <?php endif; ?>
        </div>
    </div>
<span class="cma_poweredby"><a href="http://www.cminds.com/" target="_new" class="cma_poweredbylink">CreativeMinds WordPress Plugin</a> <a href="http://www.cminds.com/plugins/cm-answers/" target="_new" class="cma_poweredbylink">Answers</a></span>
</div>
<div id="secondary" role="complementary" class="widget-area">
    <?php dynamic_sidebar('cm-answers-sidebar'); ?>
</div>
<?php
get_footer();
?>