<?php
/**
 * CM Answers about page
 *
 * @author CreativeMinds (http://www.cminds.com)
 * @copyright Copyright (c) 2013, CreativeMinds
 * @package Answers/View
 */
?>
<p class="clear">
<br />

This plugin was developed by <a href="http://www.cminds.com/" target="new">CreativeMinds</a>. You can find more information about CM Answers <a href="http://www.cminds.com/plugins/" target="new">here</a>
<br /><br />
<h3>More Plugins by CreativeMinds</h3>

<ul>
<li><a href="http://wordpress.org/extend/plugins/enhanced-tooltipglossary/" target="new">CM Enhanced ToolTip Glossary</a> - Parses posts for defined glossary terms and adds links to the static glossary page containing the definition and a tooltip with the definition.</li> 
<li><a href="http://wordpress.org/extend/plugins/multi-mailchimp-list-manager/" target="new">CM Multi MailChimp List Manager</a> - Allows users to subscribe/unsubscribe from multiple MailChimp lists. </li>
<li><a href="http://wordpress.org/extend/plugins/cm-invitation-codes/" target="new">CM Invitation Codes</a> - Allows more control over site registration by adding managed groups of invitation codes.</li>
<li><a href="http://wordpress.org/extend/plugins/cm-email-blacklist/" target="new">CM Email Blacklist</a> - Block users from blacklists domain from registering to your WordPress site.</li>
<li><a href="http://wordpress.org/extend/plugins/cm-download-manager" target="new">CM Download Manager</a> - Allow users to upload and manage Downloads in a directory structure for others users to use and comment.</li>
</ul>
<br />
<h3>We Expert in Custom Plugin Development</h3>
<ul>
<li><strong>Professional Quality Work </strong>- We follow a detailed coding standard that ensures we deliver only the highest quality products and services. You can count on maintainable code that fulfills your requirements completely.</li>
<li><strong>Expert Knowledge </strong>- Custom WordPress plugin is our specialty. We devote a lot of work to deliver bug free products. We use WP custom functions and we excel in PHP / SQL / JQuery/ Ajax</li>
<li><strong>Integration with 3rd-party</strong>- We integrate upon request with external 3-rd party tools and services such as GoToMeeting, Vimeo and many others.</li>
<li><strong>Fixed Price Quotes </strong>- We provide fixed price quotes so you know exactly what your total and final development cost will be.</li>
<li><strong>Support and Warranty </strong>- Once your plugin is completed we will not leave you out in the cold. We believe that your success is our success and we want a happy customer who will use us again. You and your Plugin will be fully supported for 3-Months Warranty.</li>

</ul>
</p>