<p class="clear">
<br />
<h1><strong>CM Answers Pro </strong></h1>
 <p><strong>A Pro version of CM Answers is <a href="http://www.cminds.com/downloads/cm-answers-pro/"  target="new">available here</a></strong></p>
 <p>CM Answers Pro is a Premium version of <a title="CM Answers" href="http://www.cminds.com/plugins/cm-answers/" target="new">CM Answers</a></p>
This plugin adds many more features and functionality to <a title="CM Answers" href="http://www.cminds.com/cm-answers/" target="new">CM Answers Plugin</a>, giving the admin better tools to customize the Answers system behavior, adding login support from social networks, adding shortcodes and support for categories and a lot more.
<h2>Features (Pro Version Only)</h2>
<ul>
	<li><strong>Social Media Integration</strong>- Integrates with Facebook &amp; Google+ &amp; LinkedIn </li>
	<li><strong>Shortcodes</strong>- You can generate questions list by using shortcode: cma-questions with additional parameters. For example limit=10 author=123 sort=hottest</li>
	<li><strong>User Questions &amp; Answers</strong>- You can add "My Questions" and "My Answers" profile views per user anywhere on the site by using shortcodes: cma-my-questions and cma-my-answers</li>
	<li><strong>Categories</strong>- Ability to add categories and display on different pages in site by using shortcode cat=catname</li>
	<li><strong>Widgets</strong>- Added Widget which can display hotest questions, most viewed, recent and more</li>
	<li><strong>User Posting Meter</strong>- Ability to add near each user  number of questions and answers already posted </li>
	<li><strong>Show/Hide Views</strong>- Admin can hide or show number of views</li>
	<li><strong>Auto-approve questions and answers from users</strong>- Admin can define list of users which do not need moderation</li>
	<li><strong>Multisite</strong>- Supports multisite</li>
	<li><strong>User Profile</strong>- Automaticly generate a profile page per each user containing the questions and answers he posted with link to social media profile</li>
	<li><strong>Gratitude Message</strong> - Does not include Gratitude message in the footer.</li>
</ul>
<h1><strong>Purchase </strong></h1>
<p>The Pro version is only $25. You can purchase the pro version from <a href="http://www.cminds.com/downloads/cm-answers-pro/">Here</a></p>


</p>