<p class="clear">
<br />
<h1><strong>CM Answers Pro </strong></h1>
 <p><strong>A Pro version of CM Answers is <a href="http://answers.cminds.com/"  target="new">available here</a></strong></p>
 his plugin adds many more features and functionality to <a title="CM Answers" href="http://answers.cminds.com/" target="new">CM Answers Plugin</a>, giving the admin better tools to customize the Answers system behavior, adding login support from social networks, adding shortcodes and support for categories and a lot more.
<h2>Features (Pro Version Only)</h2>
<ul>
<ul>
<li><strong>Social Media Integration</strong>- Integrates with Facebook &amp; Google+ &amp; LinkedIn (<a href="http://www.cminds.com/wp-content/uploads/edd/image1.png" target="new">image-1</a>) (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image2.png" target="new">image-2</a>)</li>
<li><strong>Shortcodes</strong>- Generate questions list by using shortcode: cma-questions with additional parameters. For example limit=10 author=123 sort=hottest (<a href="http://answers.cminds.com/cm-answers-shortcode-example/" target="new">Demo</a>)</li>
<li><strong>User Dashboard</strong>- Add "My Questions" and "My Answers" dashboards to user profile page by using shortcodes: cma-my-questions and cma-my-answers (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image3.png" target="new">image</a>)</li>
<li><strong>Categories</strong>- Ability to add categories and display by using shortcode cat=catname  (<a href="http://answers.cminds.com/cm-answers-shortcode-example/" target="new">Demo</a>),  (<a href="http://answers.cminds.com/answers" target="new">Demo in Questions Index</a>)</li>
<li><strong>Widgets</strong>- Widget can display hottest questions, most viewed, recent and more (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image4.png" target="new">image</a>), (<a href="http://answers.cminds.com/answers" target="new">Demo in Questions Index</a>)</li>
<li><strong>User Posting Meter</strong>-Ability to add beside  each user profile the number of questions and answers that contributor has already posted  (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image5.png" target="new">image</a>)</li>
<li><strong>Show/Hide Views</strong>- Admin can hide or show number of views (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image6.png" target="new">image</a>)</li>
<li><strong>Moderation</strong>- Admin can define list of users which do not need moderation (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image7.png" target="new">image</a>)</li>
<li><strong>Multisite</strong>- Supports multisite</li>
<li><strong>Public User Profile</strong>- Automatically generate a public profile page containing the questions and answers user posted with link to his social media profile (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image8.png" target="new">image</a>), (<a href="http://answers.cminds.com/contributor/admin/" target="new">Demo</a>)</li>
<li><strong>Gravatar</strong> - Ability to show Gravatar near user name and in user profile</li>
<li><strong>Order Answers</strong> - Show all answers in ascending or descending order  (<a href="http://answers.cminds.com/wp-content/uploads/edd/Answers99D" target="new">Image from Settings</a>)</li>
<li><strong>Attachments</strong> - Accept file attachment in question, limit by file type and size (<a href="http://answers.cminds.com/wp-content/uploads/edd/Answers99A.png" target="new">Image</a>), (<a href="http://answers.cminds.com/wp-content/uploads/edd/Answers99B" target="new">Image from Settings</a>)</li>
<li><strong>Localization Support</strong> - Forntend (user side) is localized</li>
<li><strong>View Count Control</strong> - Control how view count is done (by view or by session)  (<a href="http://answers.cminds.com/wp-content/uploads/edd/Answers99C" target="new">Image from Settings</a>)</li>
<li><strong>Ajax Support</strong> - Using Shortcode to display Category now supports Ajax and fits intself into current site templet. <a href="http://jumpstartcto.com/cm-answers-ajax-example" target="new">See Example</a></li>
<li><strong>Gratitude Message</strong> - Does not include Gratitude message in the footer.</li>
<li><strong>Tags</strong> - Tags are support. Admin can control the appearance of tags. Tags widget is also available  (<a href="http://answers.cminds.com/answers" target="new">Demo - Widget on the right</a>),  (<a href="http://answers.cminds.com/wp-content/uploads/edd/Answers99E" target="new">Image</a>)</li>
<li><strong>Sticky Questions</strong> -  Support sticky questions with admin defined background color (<a href="http://answers.cminds.com/answers" target="new">Demo - First question is sticky</a>),  (<a href="http://answers.cminds.com/wp-content/uploads/edd/Answers99F" target="new">Image When Admin edit question post</a>) ,  (<a href="http://answers.cminds.com/wp-content/uploads/edd/Answers99H" target="new">Image from settings</a>)</li>
<li><strong>Accept Code Snippets</strong> - Support code snippets with defined background color  (<a href="http://answers.cminds.com/answers/code-example/" target="new">Demo of code inside a question</a>),  (<a href="http://answers.cminds.com/wp-content/uploads/edd/Answers99G" target="new">Image from settings</a>)</li>
<li><strong>Home Page</strong> - Support option to define cm answers as site/blog homepage  (<a href="http://answers.cminds.com/wp-content/uploads/edd/Answers99M" target="new">Image from settings</a>) </li>
<li><strong>Permalink</strong> - Customize CM Answers permalink  (<a href="http://answers.cminds.com/wp-content/uploads/edd/Answers99N" target="new">Image from settings</a>) </li>
<li><strong>Disclaimer</strong> - Added Disclaimer support for first time users (<a href="http://answers.cminds.com/wp-content/uploads/edd/Answers99O" target="new">Image from settings</a>) , (<a href="http://answers.cminds.com/wp-content/uploads/edd/Answers99P" target="new">Image when disclaimer appears</a>) </li> <li><strong>Social Share</strong> - Includes a social share widget in the question page (<a href="http://answers.cminds.com/answers/code-example/" target="new">Demo</a>)  </li></ul>

<h1><strong>Purchase </strong></h1>
<p>The Pro version is only $25. You can purchase the pro version from <a href="http://answers.cminds.com/">Here</a></p>


</p>