<div class="cma-upgrade">
	<h3>Want more? Get the PRO</h3>
	<p>Professional version of CM Answers which gives the admin better tools to customize the Answers system behavior,
	adding login support from social networks, adding shortcodes and support for categories and a lot more.</p>
	<a href="<?php echo esc_attr(admin_url('admin.php?page='. CMA_BaseController::ADMIN_PRO)); ?>" class="button button-primary">Upgrade to PRO</a>
</div>