<div class="clear"></div>

<p><strong>A Pro version of <?php echo CMOB_NAME; ?> is <a href="https://plugins.cminds.com/cm-onboarding-plugin-wordpress/" target="_blank" class="button button-primary">available here</a></strong></p>

<hr/>

<div>
    <h3>Features (Pro Version Only)</h3>
    <ul>
        <li><strong>Show Widget On Limited Set of Pages</strong> - Instead of just having one set of Help Items, you can create multiple and even choose to have different one on each page!</li>
        <li><strong>Multiple Icons</strong> - You can choose from multitude of the icons from our designers, available in two themes (white & grey)</li>
        <li><strong>Custom Icon</strong> - For even more customisation you can provide a link to your own icon and the plugin will use it instead!</li>
        <li><strong>Multiple Widget Types</strong> - The sliding panel stays the same, but the help items can be displayed with Select box, Side menu or as a Slider!</li>
        <li><strong>Widget Themes</strong> - The pro version comes with the ability to choose the theme of the Widget</li>
        <li><strong>Header/Footer for Widgets</strong> - Want to show a logo? A copyright notice? In the Pro version you can add any HTML you like both above and below the content!</li>
        <li><strong>Search in the Widgets</strong> - Allow your users to quickly find what they want with very fast internal search which will leave only the related items visible.</li>
        <li><strong>Templates</strong> - We've created a possibility to create a template content and share it across multiple Help Items. Change in one place and everything's synchronised.</li>
    </ul>
</div>

<hr/>

<div>
    <h3>Purchase <?php echo CMOB_NAME; ?> Pro</h3>
    <p> <a href="https://plugins.cminds.com/cm-onboarding-plugin-wordpress/" target="_blank" class="button button-primary">Buy Now!</a> </p>
</div>